backend:
  name: git-gateway
  branch: "main"
  repo: ZINWEBB/homeweb

media_library:
  name: cloudinary
  config:
    cloud_name: "homerigz"
    api_key: "547679675493895"

collections:
  - name: "houselisting"
    label: "House Listings"
    folder: ""
    files:
      - file: "HOMELINK-JS/houselisting.json"
        label: "House Listings"
        name: "houselisting"
        fields:
          - label: "House Listing"
            name: "houselisting"
            widget: "list"
            fields:
              - {label: "ID", name: "id", widget: "string"}
              - {label: "Venue", name: "venue", widget: "string"}
              - {label: "Location", name: "location", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Basic Fee", name: "basicFee", widget: "number"}
              - {label: "Agent Fee", name: "agentFee", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Total Fee", name: "totalFee", widget: "number"}
              - {label: "Service Type", name: "servicetype", widget: "string"}
              - label: "Gallery"
                name: "gallery"
                widget: "list"
                fields:
                  - {label: "Image URL", name: "image", widget: "image"}
              - {label: "Bed Space", name: "bedspace", widget: "string"}
              - {label: "Bath Space", name: "bathspace", widget: "string"}
              - {label: "Compound Space", name: "compoundspace", widget: "string"}
              - {label: "Inspection Fee", name: "inspection", widget: "number"}

